---
title: "SAEM function tutorial"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---
  
<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.weightedidth = 12,
               fig.asp = 0.8,
               out.weightedidth = "100%")

folder <- '../../R/'
source('../../R/include.R')
```

## Initialisation et génération des données

```{r number of cores, echo = F}
ncores <- pmin(1, future::availableCores()-1 )

message(paste('number of cores available =', ncores))
print(paste('number of cores available =', ncores))
```

```{r init}
m <- function(t, eta, phi) phi[,1] * t + eta
#=======================================#
param <- list( sigma2 = 0.5,  #variance de l'erreur
               rho2 = 0.05,
               mu = 3,  #moyenne de phi
               omega2 = 0.1 )  #variance de phi

F. <- length(param$omega2) #dimension de phi
#=======================================#
t <- seq(2,6, length.out = 10) #value of times

# --- longitudinal data --- #
G = 40 ; ng = 12 #nombre de groupe et d'individu par groupe
n <- G*ng*length(t) ; N <- G*ng  #nombre total de data, et #nombre total d'individu

dt_NLME <- NLME_obs(G, ng, t, param, m)
Y <- dt_NLME$obs
```

```{r data ploting, echo = F}
dt_NLME %>% ggplot(aes(t, obs, col = gen, group = id)) + 
  geom_point() + geom_line() + theme(legend.position = 'null')
```

# Statistique exhaustive
$$\log f(Y, Z ; \theta) = \langle \Phi(\theta) ; S(Y,Z) \rangle - \psi(\theta)$$

```{r stat exhaustive}
#Petite fonction pour retourner rapidement l'appel Phi[attr(Phi, i)] où i est '1', '2', ...,
`%a%` <- function(x,var){
  if(length(var)== 1) return(x[ attr(x,as.character(var)) ])
  lapply(var, function(v) x%a%v) %>% unlist
}

Phi <- function(sigma2,rho2, mu, omega2)
{
  p <- c(- n/(2*sigma2), -N/(2*rho2), -G/(2*omega2), G*mu/omega2)
  
  attr(p, '1') <- 1
  attr(p, '2') <- 2
  attr(p, '3') <- 2 + 1:length(mu)
  attr(p, '4') <- 2 +   length(mu) + 1:length(mu)
  return(p)
}

S <- get_stat(function(eta, phi) mean((Y - get_obs(m, dt_NLME, eta = eta, phi = phi) )^2 ),
              function(eta, phi) mean(eta^2),
              function(eta, phi) apply(phi^2, 2, mean),
              function(eta, phi) apply(phi  , 2, mean), dim = c(1,1,F., F.) )
```
# Metropolis Hastings

## Vraisemblance

```{r MH}
loglik.phi <- function(x, eta, Phi)
{
  id <- c(1,3,4) #indice de S_1 et S_{3,.} puis S_{4,.}
  sum( Phi%a%id * S(eta, x, i = id) )
}
loglik.eta <- function(x, phi, Phi) 
{ 
  id <- c(1,2)
  sum( Phi%a%id * S(x, phi, i = id) )
}
```

# SAEM
## initialisation
```{r SAEM init}
M <- 1 #nombre de simulation

# ---  Initialisation des paramètres --- #
para <- list( sigma2 = 0.1,
              rho2 = 0.5,
              mu = 4,
              omega2 = 0.3 )

# --- Initialisation des chaines MC : Z_0 ---
Z <- list(eta = 1:M %>% lapply(function(i) rnorm(G*ng, 0, para$rho2)  %>% matrix(ncol = 1) ),
          phi = 1:M %>% lapply(function(i) matrix(rnorm(F.*G, para$mu, para$omega2), nrow = F.) %>% t ) )
```

## Etape simulation et maximisation du SEAM
```{r SAEM fct}
sim <- function(niter, Phih, eta, phi)
{
  M <- length(phi)

  eta <- 1:M %>% lapply( function(i)
    MH_High_Dim_para_future(niter, eta[[i]], sd = .03, loglik.eta, phi[[i]], Phih, cores = ncores ))
  
  phi <- 1:M %>% lapply( function(i)
    MH_High_Dim_para_future(niter, phi[[i]], sd = .02, loglik.phi, eta[[i]], Phih, cores = 1 ))
  
  list(eta = eta, phi = phi)
}

maxi <- function(S)
{
  list(sigma2 = S%a%1,
       rho2 =   S%a%2,
       mu =     S%a%4,
       omega2 = S%a%3 - (S%a%4)^2 )
}
```

# Resultats

```{r oracle, echo = F, results='asis'}
data.frame( Oracle = S(attr(dt_NLME, 'eta'), attr(dt_NLME, 'phi')) %>% maxi %>% unlist ,
            Initialisation = para%>% unlist)%>% t %>% 
  knitr::kable(format = 'html') %>% kable_styling(full_width = F)
```

```{r SAEM loop }
niter <- 300
MH.iter <- 10

res <- SAEM(niter, MH.iter, para, Phi, S, Z, sim, maxi, 
            burnin = 150, coef.burnin = 3/4, eps = 1e-3, verbatim = 2)
saveRDS(res, 'saem.rds')
gg <- plot(res)
```

```{r seam table, results='asis', echo = F }
gg$table_estimation
```

```{r saem plot, echo = F }
gg$plot_paramater
gg$plot_MCMC

gg.MH <- names(res$Z) %>% keep(function(var) 'MH_res' %in% class(res$Z[[var]][[1]]) ) %>%
  lapply(function(var)plot(res$Z[[var]][[1]], name = var)$plot_acceptation)

grid.arrange(grobs  = gg.MH)
```
