---
title: "Longitudinal and non-linear mixed effect model"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 12, fig.asp = 0.8,
               fig.align = "center",
               out.weightedidth = "50%")

library(SAEM4JLS)
```

## Initialisation

```{r number of cores, echo = F}
ncores <- pmin(1, future::availableCores() )
message(paste('number of cores available =', ncores))
print(paste('number of cores available =', ncores))
```

```{r init}
#Phi[1] ; eta = valeur de fin  Phi[2] = valeur du noeud  Phi[3] = echelle
m <- function(t, eta, phi) (phi[,1] + eta)/(1+exp((phi[,2]-t)/phi[,3]))
#=======================================#
#=======================================#
param <- list(sigma2 = 0.05,
              rho2 = 0.1,
              mu = c(5,90,5),
              omega2 = c(0.5,0.1,0.01) )

#=======================================#
t <- seq(60,120, length.out = 10) #value of times

# --- longitudinal data --- #
set.seed(18031997)
data <- NLME_data(G = 20, ng = 8, time = t, fct = m, param = param)

getDim(data)
Y <- data$obs
```

```{r data ploting, echo = F} 
plot(data) 
```

## SAEM avec simulation par MCMC
$$\log f(Y, Z ; \theta) = \langle \Phi(\theta) ; S(Y,Z) \rangle - \psi(\theta)$$

```{r  stat exhaustive}
Phi <- fct_vector(function(sigma2, rho2, mu, omega2) 
  c(-n/(2*sigma2), -N/(2*rho2), -G/(2*omega2), mu), dim = c(1,1,F.,F.) )$eval

S <- fct_vector(function(eta, phi) mean((Y - get_obs(data, eta = eta, phi = phi) )^2 ),
                function(eta, ...) mean(eta^2),
                function(phi, ...) apply(phi^2, 2, mean),
                function(phi, ...) apply(phi  , 2, mean), dim = c(1,1,F.,F.) )
```

## Metropolis Hastings

```{r MH}
loglik.phi <- function(x, eta, Phi)
{
  id <- c(1,3,4) #indice de S_1 et S_{3,.} puis S_{4,.}
  sum(Phi%a%1*S$eval(eta = eta, phi = setoffset(x, Phi%a%4), i = 1) + Phi%a%3 * S$eval(phi = x, i = 3) )
}
loglik.eta <- function(x, phi, Phi) 
{ 
  id <- c(1,2)
  sum( Phi%a%id * S$eval(eta = x, phi = phi, i = id) )
}
```

## SAEM
## Initialisation
```{r SAEM init}
# ---  Initialisation des paramètres --- #
para <- param %>% lapply(function(x) x* runif(1, 1,1.2))
para$rho2 = 0.2 ; para$omega2 <- rep(.1,3)



# --- Initialisation des chaines MC : Z_0 ---
Z <- list(eta = list( matrix(rep(0, G*ng), ncol = 1) ),
          phi = list( matrix(rep(para$mu, G), nrow = F.) %>% t ) )
```

## Etape simulation et maximisation du SEAM

```{r SAEM fct}
sim <- function(niter, h, Phih, eta, phi, verbatim = F)
{
  M <- length(phi)
  eta <- 1:M %>% lapply( function(i)
    MH_High_Dim_future(niter, eta[[i]], sd.eta , loglik.eta, phi[[i]], Phih, 
                            cores = 1, verbatim = verbatim))
  
  phi <- 1:M %>% lapply( function(i)
    MH_Gibbs_Sampler_future(niter, setoffset(phi[[i]],-Phih%a%4), sd.phi, loglik.phi, eta[[i]], Phih, 
                            cores = 1, verbatim = verbatim )) %>%
    lapply(setoffset, Phih%a%4)
  
  list(eta = eta, phi = phi)
}

maxi <- function(S)
{
  list(sigma2 = S%a%1,
       rho2 =   S%a%2,
       mu =     S%a%4,
       omega2 = S%a%3 - (S%a%4)^2 )
}
```

```{r oracle, echo = F, results='asis'}
data.frame( Oracle = oracle(maxi, S, data) %>% unlist ,
            Initialisation = para%>% unlist)%>% t %>% 
  knitr::kable(format = 'html') %>% kable_styling(full_width = F)
```

```{r SAEM loop }
niter <- 200
MH.iter <- 10

sd.eta <- .3
sd.phi <- c(.05, .3, .05)

gg <- simulation_test(sim, Phi, param, 100, Z) %>% lapply(function(z)plot(z[[1]], nrow = 2))

res <- SAEM(niter, MH.iter, para, Phi, S$eval, Z, sim, maxi,
            burnin = 100, coef.burnin = 2/3, verbatim = 2)

saveRDS(res, 'saem.rds')
```

```{r seam table, results='asis', echo = F }
plot(res, true.value = oracle(maxi, S, data), var = 'summary')
```

```{r saem plot, echo = F }
plot(res, true.value = oracle(maxi, S, data) )
plot.fitted.value(res, data)#, 1:100)
```



