---
title: "JLS - one dim - SAEM"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

knitr::knit_hooks$set(time = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now, units = 's')
      # return a character string to show the time
      diff_time <- format(as.POSIXct(as.numeric(res), 
                                     origin = '1970-01-01', tz = 'UTC'), "%Mmin %Ssec")
      paste("Chunk execution time = ", diff_time)
    }
  }
}))

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 10,
               fig.asp = 0.8,
               out.width = "100%")

require(SAEM4JLS)
require(tictoc)
```



```{r}
# Exemple d'optimalité entre les 3 fct MH, MH_high_dim et MH_high_dim_para sur le modèle non lineaire mixte
m <- function(t, phi1, phi2, phi3) (phi1  )/(1+exp((phi2-t)/phi3))
#=======================================#
p <- 1
param <- list(sigma2 = .05^2,
              #rho2 = 5,
              mu = c(0.9,90,5),
              omega2 = c(0.005, 40, 1),
              #S.data data,
              bara = 90,
              barb = 30,
              baralpha = 0.5,
              beta = 10)

#=======================================#
t <- seq(60,120, length.out = 10) #time values
set.seed(123)

G <- 40 ; ng = 4
link = function(t,phi1, phi2, phi3) phi2#/phi3

dt <- create_JLS_HD_data(G, ng, t, m, link, param)

var.true <- dt$var.true 
S.data <- dt$survival
U <- dt$U

Y <- do.call(get_obs, var.true) + rnorm(n, 0, sqrt(param$sigma2))
S.data.time <- S.data$obs
S.data.time.log.sum <- sum(log(S.data.time))
```

```{r data ploting, eval=FALSE, include=FALSE}
longitudinal_plot <- data.frame(time, Y, id = rep(1:N, each = length(t)), gen = rep(1:G, each = ng*length(t)) ) %>%
  ggplot(aes(time, Y, col = factor(gen), group = factor(id) )) +
  geom_point() + geom_line() +
  theme(legend.position = 'null')

S.data_plot <- S.data %>% ggplot(aes(obs)) +#, fill = U))) +
    geom_histogram(col = 'white', position = 'identity', bins = 30) + theme(legend.position = 'null')

grid.arrange(longitudinal_plot, S.data_plot, nrow = 2)
```

```{r, echo = F}
sigma2_a <- sigma2_b <- sigma2_alpha <- 0.1

h <- fct_vector(function(a,b, ...) N*log(b*a^-b),
                function(b, ...) (b-1)*S.data.time.log.sum,
                function(phi1, phi2, phi3, ...) sum(link(S.data.time, rep(phi1, ng), rep(phi2, ng), rep(phi3, ng) )) 
                )

zeta <- function(beta, alpha, phi1, phi2, phi3, a,b)
{
  link.fct <- function(t,g) link(t, phi1[g], phi2[g], phi3[g])
  link.value <- sapply(1:nrow(S.data), function(i) link.fct(S.data$obs[i], S.data$gen[i]) )
  
  P1 <- as.vector(exp(beta %*% t(U)))
  
  P2 <- sapply(1:nrow(S.data), 
               function(i)integrate(
                 function(t) t^(b-1)*exp(alpha*link.fct(t, S.data$gen[i])),
                 0, S.data$obs[i])$value
               )
  
  sum(beta%*%t(U) + alpha*link.value - b*a^-b * P2*P1)
}

zeta.B <-  function(beta, alpha, phi1, phi2, phi3, a,b) - zeta(beta, alpha, phi1, phi2, phi3, a,b)/N
zeta.der.B <- function(beta, i, alpha, phi1, phi2, phi3, a, b)
{
  g <- S.data$gen[i]
  link.fct <- function(t) link(t, phi1[g], phi2[g], phi3[g])
  
  P1 <- U[i,] * exp(sum(beta * U[i,]))
  
  P2 <- integrate(function(t) t^(b-1)*exp(alpha*link.fct(t) ),
                  0, S.data$obs[i])$value
  
  -(U[i,] - b*a^-b * P1*P2)
}
```

```{r eval=FALSE, include=FALSE}
res <- SPGD(4*200, theta0 = rep(0,p),
      step = burnin_fct(150, coef.burnin = 0.1, scale = 1e-2 ),
      mini.batch.size = 5,
      zeta.der.B, N, zeta.B,
      param$alpha,  var.true$phi1, var.true$phi2, var.true$phi3, var.true$a,var.true$b, verbatim = T)

as.numeric(res)
zeta(as.numeric(res), param$alpha,  var.true$phi1, var.true$phi2, var.true$phi3, var.true$a,var.true$b)
zeta(param$beta, param$alpha,  var.true$phi1, var.true$phi2, var.true$phi3, var.true$a,var.true$b)

zeta.der.B(param$beta, 3, param$alpha,  var.true$phi1, var.true$phi2, var.true$phi3, var.true$a,var.true$b)
```

```{r}
model <- SAEM_model( 
  function(sigma2, ...) -n/(2*sigma2),
  function(phi1, phi2, phi3, ...) mean((Y - get_obs(phi1, phi2, phi3) )^2 ), 'sigma2',
  
  # === Variable Latente === #
  latent_vars = list(
    # === Non linear model === #
    latent_variable('phi', dim = G, size = 3, prior = list(mean = 'mu', variance = 'omega2'),
                    add_on = c('zeta(phi1 = phi1, phi2 = phi2, phi3 = phi3, ...)' )),
    
    # === S.data model === #
    latent_variable('a', prior = list(mean = 'bara', variance.hyper = 'sigma2_a'),
                    add_on = c('zeta(a = a, ...) +',
                               'h$eval(a = a, ..., i = 1)')),
    latent_variable('b', prior = list(mean = 'barb', variance.hyper = 'sigma2_b'),
                    add_on = c('zeta(b = b, ...) +',
                               'sum(h$eval(b = b, ..., i = c(1,2)))' )),
    latent_variable('alpha', prior = list(mean = 'baralpha', variance.hyper = 'sigma2_alpha'),
                    add_on = c('zeta(alpha = alpha, ...) +',
                               'alpha*h$eval(alpha = alpha,..., i = 3)'))
  ),

  # === Paramètre de regression === #
  regression.parameter = list(
    regression_parameter('beta', 1, function(...) SPGD(10, theta0 = beta,
                                                      step = burnin_fct(150, coef.burnin = 0.1, scale = 1e-2 ),
                                                      mini.batch.size = 5,
                                                      zeta.der.B, N, zeta.B, 
                                                      Z$alpha,  Z$phi1, Z$phi2, Z$phi3, Z$a,Z$b) )
  )
)
```

```{r saem load}
# ---  Initialisation des paramètres --- #
param0 <- param %>% sapply(function(x) x* runif(1, 1.1,1.4))
#param0$rho2 = 0.2 ; param0$omega2 <- rep(.1,3)
param0$bara <- 80 ; param0$barb <- 10
param0$sigma2 <- 1
param0$beta <- rep(0.5,p)
param0$baralpha <- 0.1
#===============================================#
load.SAEM(model)#, exclude.maximisation = c('beta'))
var0 <- init.SAEM(model, 
                  x0 = list(phi = c(1,80,4), 
                            a = param0$bara, b = param0$barb, alpha = param0$baralpha), 
                  sd = list(phi = c(.05, 1.5, .5),
                            a = 2, b = 1, alpha = .1) )
#===================================================================================#
S.tmp <- do.call(S$eval, var.true)
oracle <- maximisation(1, do.call(S$eval, var.true), param, var.true)
oracle %>% unlist
```
# saem
```{r saem}
load.SAEM(model)#, exclude.maximisation = 'beta')
# sim(50, var1, Phi, param, verbatim = 2) %>% plot(nrow = 2)

res <- SAEM(200, 5, param0, var0, Phi, S$eval, maximisation, simulation,  eps = 1e-3,
            burnin = 450, 
            adptative.sd = 0.6, verbatim = 3, RDS = T )
```

```{r plot, echo = F, fig.asp=0.8, fig.width=8}
plot(res, true.value = oracle, exclude = 'beta')
plot_high_dim(res, oracle, 'beta', dec = 0)
plot(res, true.value = oracle, var = 'summary', exclude = 'beta', time = F)
```

