---
title: "Proof of concept for proximal gradient descent in maximization step in SAEM"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

knitr::knit_hooks$set(time = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now, units = 's')
      # return a character string to show the time
      diff_time <- format(as.POSIXct(as.numeric(res), 
                                     origin = '1970-01-01', tz = 'UTC'), "%Mmin %Ssec")
      paste("Chunk execution time = ", diff_time)
    }
  }
}))

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 12,
               fig.asp = 0.8,
               out.width = "100%")

require(SAEM4JLS)
require(tictoc)
```



```{r}
parameter <- list(sigma2 = 0.5,
              rho2 = .5,
              mu = 3)

J <- 10 ; n <- 50 ; p <- 200

time <- seq(-1,1, len = J)
ttime <- t(time)

U <- matrix(runif(n*p, min = -1, max = 1), nrow = n, ncol = p)

expand.grid(n = 1:n, p = 1:p) %>% mutate(U = as.numeric(U)) %>%
  ggplot(aes(n,p, fill = U)) + geom_tile() + scale_fill_gradient2()


tU <- t(U)
parameter$beta <- rep(0,p)
parameter$beta[1:4] <- c(1,2,-1,-2)*1

eps <- matrix(rnorm(n*J, sd = sqrt(parameter$sigma2)), nrow = n)
slope <- rnorm(n, parameter$mu, sd = sqrt(parameter$rho2))

Y <- as.vector(parameter$beta %*% tU) + slope %*% ttime + eps
```

```{r data ploting, echo = F}
data.frame(Y) %>% mutate(id = 1:n) %>%
  melt(id = 'id', value.name = 'Y') %>%
  mutate(variable = rep(time, each = n)) %>% rename(time = variable) %>%
  ggplot(aes(time, Y, col = factor(id))) + geom_line() + theme(legend.position = 'null')
```


```{r SPGD res}
l <- function(beta, slope, parameter, ... ) 1/(2*parameter$sigma2) * sum( (Y - as.vector(beta %*% tU) - slope %*% ttime )^2 ) 
grad.li <- function(beta, i, slope, ...) -1/parameter$sigma2 * sum(Y[i,] - sum(beta * U[i,]) - slope[i]*time) * U[i,]
```


```{r SPGD test}

res <- SPGD(400, theta0 =  runif(p, min = -1, max = 1),
            normalized.grad = T,
            step = burnin_fct(390, coef.burnin = 0.5, scale = 0.5 ),
            grad.li, n, l, slope, parameter, verbatim = T)


plot(as.numeric(res))

plot(attr(res, 'f.value'))
matplot(attr(res, 'gradf.value') )


plot(res, seq(-0.5,1.5, len = 100), l, grad.li, 1, n, slope, parameter)
plot(res, seq(-0.5,1.5, len = 100), l, grad.li, 2, n, slope, parameter)
plot(res, seq(-0.5,1.5, len = 100), l, grad.li, 3, n, slope, parameter)
plot(res, seq(-0.5,1.5, len = 100), l, grad.li, 4, n, slope, parameter)
plot(res, seq(-0.5,1.5, len = 100), l, grad.li, 5, n, slope, parameter)

l(parameter$beta, slope, parameter)
l(res, slope, parameter)

sapply(1:n,function(i) grad.li(res, i, slope)) %>% apply(1, mean)

mean(abs(as.numeric(res) %*% tU - parameter$beta%*% tU)/parameter$beta%*% tU)
mean(abs(as.numeric(res) - parameter$beta))



```

```{r SAEM model}
model <- SAEM_model(
  function(sigma2, ...) - n*J/(2*sigma2),
  function(slope, beta, ...) mean( (Y - as.vector(beta %*% tU) - slope %*% ttime )^2 ),
  noise.name = 'sigma2',

  # === Variable Latente === #
  latent_vars = list(
    latent_variable('slope', dim = n, prior = list(mean = 'mu', variance = 'rho2'))
  ),

  # === Paramètre de regression === #
  regression.parameter = list(
    regression_parameter('beta', p, function(...) SPGD(1, theta0 = beta,
                                                      step = 1e-2, mini.batch.size = 1,
                                                      grad.li, n, l, Z$slope, parameter) )
  )
)
```







```{r SAEM}
load.SAEM(model)
var0 <- init.SAEM(model,
                  x0 = list(slope = 0),
                  sd = list(slope = .3))


parameter0 <- list(sigma2 = 0.1, rho2 = 0.4, mu = 2.8, beta = rep(0, p))
oracle <- max(S = do.call(S$eval, c(parameter, list(slope=slope)) ), parameter = parameter, Z = list(slope=slope))

sim(200, var0, Phi, parameter, verbatim = 2) %>% plot(nrow = 2)



res <- SAEM(200, 10,
            parameter0, var0, Phi, S$eval, max, sim,
            adptative.sd = 0.6,
            burnin = 150,
            verbatim = 3)

plot(res, true.value = oracle, var = 'special', exclude = 'beta')

plot_high_dim(res, oracle, 'beta', dec = 0)

plot(res, true.value = oracle, var = 'summary', exclude = 'beta', time = F)

res[200]$beta
```

























