---
title: "grad of zeta debug"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 10,
               fig.asp = 0.8,
               out.width = "100%")

require(SAEM4JLS)
require(tictoc)
```



```{r}
# Exemple d'optimalité entre les 3 fct MH, MH_high_dim et MH_high_dim_para sur le modèle non lineaire mixte
m <- function(t, phi1, phi2, phi3) (phi1  )/(1+exp((phi2-t)/phi3))
#=======================================#
p <- 5
param <- list(sigma2 = .05^2,
              #rho2 = 5,
              mu = c(0.9,90,5),
              omega2 = c(0.005, 40, 1),
              #S.data data,
              bara = 90,
              barb = 30,
              baralpha = 0.5,
              beta = rep(0,p))
param$beta[1:3] <- 1
#=======================================#
t <- seq(60,120, length.out = 10) #time values
set.seed(123)

G <- 10 ; ng = 1
link = function(t,phi1, phi2, phi3) phi2#/phi3

dt <- create_JLS_HD_data(G, ng, t, m, link, param)

var.true <- dt$var.true 
S.data <- dt$survival
U <- dt$U

Y <- do.call(get_obs, var.true) + rnorm(n, 0, sqrt(param$sigma2))
S.data.time <- S.data$obs
S.data.time.log.sum <- sum(log(S.data.time))
```

```{r data ploting, eval=FALSE, include=FALSE}
longitudinal_plot <- data.frame(time, Y, id = rep(1:N, each = length(t)), gen = rep(1:G, each = ng*length(t)) ) %>%
  ggplot(aes(time, Y, col = factor(gen), group = factor(id) )) +
  geom_point() + geom_line() +
  theme(legend.position = 'null')

S.data_plot <- S.data %>% ggplot(aes(obs)) +#, fill = U))) +
    geom_histogram(col = 'white', position = 'identity', bins = 30) + theme(legend.position = 'null')

grid.arrange(longitudinal_plot, S.data_plot, nrow = 2)
```

```{r, echo = T}
sigma2_a <- sigma2_b <- sigma2_alpha <- 0.1

h <- fct_vector(function(a,b, ...) N*log(b*a^-b),
                function(b, ...) (b-1)*S.data.time.log.sum,
                function(phi1, phi2, phi3, ...) sum(link(S.data.time, rep(phi1, ng), rep(phi2, ng), rep(phi3, ng) )) 
                )

zeta <- function(beta, alpha, phi1, phi2, phi3, a,b)
{
  link.fct <- function(t,g) link(t, phi1[g], phi2[g], phi3[g])
  
  P1 <- as.vector(exp(beta %*% t(U)))
  
  P2 <- sapply(1:nrow(S.data), 
               function(i)integrate(
                 function(t) t^(b-1)*exp(alpha*link.fct(t, S.data$gen[i])),
                 0, S.data$obs[i])$value
               )
  
  - mean(beta%*%t(U) - b*a^-b * P2*P1)
}


phi1 <- var.true$phi1 ; phi2  <-  var.true$phi2 ; phi3 <-  var.true$phi3
a  <-  var.true$a ; b  <- var.true$b ; alpha <- var.true$alpha

zeta.der.B <- function(beta, i, alpha, phi1, phi2, phi3, a, b)
{
  g <- S.data$gen[i]
  link.fct <- function(t) link(t, phi1[g], phi2[g], phi3[g])
  
  P1 <- U[i,] * exp(sum(beta * U[i,]))
  
  P2 <- integrate(function(t) t^(b-1)*exp(alpha*link.fct(t) ),
                  0, S.data$obs[i])$value
  
  -(U[i,] - b*a^-b * P1*P2)
}
```



```{r}
x0 <- param$beta
x <- seq(-1,2, by = 0.01)
i <- 3
#initialization of beta values, all components are initialized to x0 except the ith component which varies between -1 and 2
x.tmp <- matrix(rep(x0, length(x)), ncol = length(x)) ; x.tmp[i,] <- x
x.tmp[,1:5]

#additional argument
args <- list(var.true$alpha,  var.true$phi1, var.true$phi2, var.true$phi3, var.true$a,var.true$b)

#calculates of the gradient for each x
grad.value = sapply(1:ncol(x.tmp), function(k) do.call(grad, list(zeta.der.B, x.tmp[,k], 1:N, args)) ) %>%
  # selects the ith component
                      { .[i,]}
```

check the documentation of grad
```{r, echo=FALSE, results='asis'}
tools:::Rd2HTML(utils:::.getHelpFile(help(grad)))
```

```{r}
grad
```

```{r}

#calculation of zeta for each x 
f.value =  sapply(1:ncol(x.tmp), function(k) do.call(zeta, c(list(x.tmp[,k]), args)) )

# some plot
dt <- data.frame(grad = grad.value, f = f.value, x = x)
grid.arrange(ggplot(dt, aes(x,f))+geom_line(),
             ggplot(dt, aes(x,grad))+geom_line())
```



