---
title: "SAEM 4 dummy linear model"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---
  
<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.weightedidth = 12,
               fig.asp = 0.8,
               out.weightedidth = "100%")

require(ggplot2)
require(reshape2)
require(dplyr)
require(tidyr)

source('R/include.R')
# require(SAEM4JLS)
```

## Initialisation

```{r init data}
m <- function(phi) phi[1] * t

ni <- 10 #nombre observation
ng <- 1 #nombre d'individu par groupe
G <- 40 # nombre groupe
F. <- 1#dimention du vecteur phi

n <- G*ng*ni #nombre total de data
N <- G*ng #nombre total d'individu

#===============================#
param <- list( sigma2 = 0.5,  #variance de l'erreur
               mu = 2,  #moyenne de phi
               omega2 = 0.5 )  #variance de phi
#===============================#

eps <- rnorm(n, 0, sqrt(param$sigma2))
phi <- 1:G %>% sapply(function(i) rnorm(F., param$mu, sqrt(param$omega2)))  %>% matrix %>% t 


X <- data.frame('gen' = rep(1:G, each = ng) %>% as.factor) #Matrice de design
t <- seq(2,6, length.out = ni) #valeur des temps

# Y_{g,i,j} = m(s_j, phi_g) + \epsilon_{g,i,j}
# Y_{i,j} = m(s_j, phi_{X[i]}) + \epsilon_{i,j}

get.Y <- function(phi) 1:N %>% sapply(function(i) m(phi[,X[i, 'gen']]))
Y <- get.Y(phi) + eps

#================================= Affichage ================================#
data.frame(Y = Y, t = t ) %>% melt(id = 't') %>% mutate(gen = rep(X$gen, each = ni)) %>%
  ggplot(aes(t, value, col = variable, shape = gen)) + geom_point() + geom_line() +#+ theme(legend.position = 'null')
  guides(color = 'none')
#============================================================================#

```


```{r res SEAM}
Phi <- function(sigma2, mu, omega2)
  c(- 1/(2*sigma2), -1/(2*omega2), mu/omega2)

S <- function(phi)
{
  s <- c(sum((Y - get.Y(phi))^2 ), #id = 1
    apply(phi^2, 1, sum),          #id = 2
    apply(phi  , 1, sum) )         #id = 3

  attr(s, '1') <- 1
  attr(s, '3') <- 1 + 1:nrow(phi)
  attr(s, '4') <- 1 + nrow(phi) + 1:nrow(phi)
  return(s)
}
#=============================================================================#
transi.phi <- function(x) rnorm(length(x), x, 0.1)

loglik.phi <- function(phi, Phi)
{
  stat <- S(phi)
  sum(Phi*stat)
}
#=============================================================================#

# --- Nombre iteration --- #
M <- 1
u <- function(k) 1
#---
para <- list( sigma2 = sample(1:5, size = 1),
              mu = rep(0, F.),
              omega2 = rep(1, F.) )

phigivenY <- 1:M %>% lapply(function(i) rnorm(F.*G, 0,1) %>% matrix(ncol = G, nrow = F.) )
#---
sim <- function(niter, Phih, phigivenY)
{
  M <- length(phigivenY)

  phigivenY <- 1:M %>% lapply( function(i)
    MH_High_Dim(niter, phigivenY[[i]], transi.phi, loglik.phi, Phih ))

  list(phi = phigivenY)
}

maxi <- function(S)
{
  mu <- S[attr(S,'4')]/G # = S[4]
  return(list(sigma2 = S[attr(S,'1')]/n,
              mu = mu,
              omega2 = S[attr(S,'3')]/G - mu^2)
  )
}

niter <- 200
Z <- list(phigivenY)
res <- SAEM(niter, 10, u, para, Phi, S, Z, sim, maxi, eps = 1e-2, verbatim = T)
```



```{r res, echo = F}
dt <- res[[1]] %>% as.data.frame %>% na.omit

#Resultat de l'estimations
est <- rbind( param %>% unlist, dt[nrow(dt),]) %>%
  t %>% data.frame

names(est) <- c('Valeur réelle', 'Valeur estimée')
  
est <- est %>%
  mutate( Rrmse = abs(`Valeur réelle` -`Valeur estimée`)/abs(`Valeur réelle`))
 
est %>% t %>%
  knitr::kable(caption = "résultat de l'algo SAEM-MCMC") %>%
  kable_styling(full_width = F)

# MCMC des paramètres
dt %>% mutate(i = 1:nrow(.)) %>% melt(id = 'i') %>%
  ggplot(aes(i, value, col = variable)) + geom_line() +
  labs(title = "représentation de l'algorithme SAEM pour les paramètres",
       x = 'iteration')

# MCMC de Z
v <- attr(res$Z, 'value')[[1]] %>% lapply(function(x) as.numeric(x)) %>% as.data.frame %>% t %>% as.data.frame()

v %>% mutate(i = 1:nrow(.)) %>% melt(id = 'i') %>% #mutate(phi = rep(factor(c(1:F.)), each = nrow(v)*G)) %>%
  ggplot(aes(i, value, col = variable)) + theme(legend.position = 'null') +
  geom_line() + 
  labs(title = "représentation des variables latentes de l'algorithme SAEM ",
       x = 'iteration')
```











