---
title: "JLS SAEM"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

knitr::knit_hooks$set(time = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now, units = 's')
      # return a character string to show the time
      diff_time <- format(as.POSIXct(as.numeric(res), 
                                     origin = '1970-01-01', tz = 'UTC'), "%Mmin %Ssec")
      paste("Chunk execution time = ", diff_time)
    }
  }
}))

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 10,
               fig.asp = 0.8,
               out.width = "100%")

require(SAEM4JLS)
require(tictoc)
```



```{r}
# Exemple d'optimalité entre les 3 fct MH, MH_high_dim et MH_high_dim_para sur le modèle non lineaire mixte
m <- function(t, phi1, phi2, phi3) (phi1  )/(1+exp((phi2-t)/phi3))
#=======================================#
param <- list(sigma2 = .05^2,
              #rho2 = 5,
              mu = c(0.9,90,5),
              omega2 = c(0.005, 40, 1),
              #Survival data,
              nu2 = 5^2,#(45 dans signal + 10 de beta)%10%
              a = 90,
              b = 30,
              alpha = 0.5,
              beta = 10)

#=======================================#
t <- seq(60,120, length.out = 10) #time values
set.seed(123)

G <- 40 ; ng = 4
link = function(t,phi1, phi2, phi3) phi2#/phi3

dt <- create_JLS_data(G, ng, t, m, link, param)

var.true <- dt$var.true 
survival <- dt$survival

Y <- do.call(get_obs, var.true) + rnorm(n, 0, sqrt(param$sigma2))
survival.time <- survival$obs
survival.time.log.sum <- sum(log(survival.time))
```

```{r data ploting, echo = F}

longitudinal_plot <- data.frame(time, Y, id = rep(1:N, each = length(t)), gen = rep(1:G, each = ng*length(t)) ) %>%
  ggplot(aes(time, Y, col = factor(gen), group = factor(id) )) +
  geom_point() + geom_line() +
  theme(legend.position = 'null')

survival_plot <- survival %>% ggplot(aes(obs, fill = factor(U))) +
    geom_histogram(col = 'white', position = 'identity', bins = 30)

grid.arrange(longitudinal_plot, survival_plot, nrow = 2)
```

```{r, echo = F}
sigma2_a <- sigma2_b <- sigma2_alpha <- 0.1

zeta <- function(beta, eta, phi1, phi2, phi3, gamma, a,b, alpha)
{
  integral <- survival$obs^b/b
  
  lbd <- function(t,g) exp(alpha*link(t, phi1[g], phi2[g], phi3[g]))
  P1 <- integral * sapply(1:nrow(survival),
                    function(i) lbd(survival$obs[i], survival$gen[i]) )
  
  P2 <- exp(beta*survival$U + as(rep(gamma, each = ng), 'matrix'))
  
  beta*sum(survival$U) -  b*a^-b * sum(P2*P1)
}

zeta.der <- function(beta, eta, phi1, phi2, phi3, gamma, a, b, alpha)
{
  lbd <- function(t,g) t^(b-1) * exp(alpha*link(t, phi1[g], phi2[g], phi3[g]))
  P1 <- 1:nrow(survival) %>% sapply(function(i) survival$obs[i]/b*lbd(survival$obs[i], survival$gen[i]) )
    # sapply(function(i) integrate(function(t) lbd(t,survival$gen[i]), 0, survival$obs[i])$value )

  P2 <- survival$U*exp(beta*survival$U + as(rep(gamma, each = ng), 'matrix'))
  
  sum(survival$U) -  b*a^-b * sum(P2*P1)
}

h <- fct_vector(function(a,b, ...) N*log(b*a^-b),
                function(b, ...) (b-1)*survival.time.log.sum,
                function(gamma,...) ng*sum(gamma),
                function(eta, phi1, phi2, phi3, ...) sum(link(survival.time, rep(phi1, ng), rep(phi2, ng), rep(phi3, ng) )) )


```


```{r}
model <- SAEM_model( 
  function(sigma2, ...) -n/(2*sigma2),
  function(phi1, phi2, phi3, ...) mean((Y - get_obs(phi1, phi2, phi3) )^2 ), 'sigma2',
  
  # === Variable Latente === #
  latent_vars = list(
    # === Non linear model === #
    latent_variable('phi', dim = G, size = 3, prior = list(mean = 'mu', variance = 'omega2'),
                    add_on = c('zeta(phi1 = phi1, phi2 = phi2, phi3 = phi3, ...)' )),
    
    # === Survival model === #
    latent_variable('gamma', dim = N, size = 1, prior = list(variance = 'nu2'),
                    add_on = c('zeta(gamma = gamma, ...) +',
                               'h$eval(gamma = gamma, ..., i = 3)')),
    
    # === Ugly parameter === #
    latent_variable('a', prior = list(mean = 'a', variance.hyper = 'sigma2_a'),
                    add_on = c('zeta(a = a, ...) +',
                               'h$eval(a = a, ..., i = 1)')),
    latent_variable('b', prior = list(mean = 'b', variance.hyper = 'sigma2_b'),
                    add_on = c('zeta(b = b, ...) +',
                               'sum(h$eval(b = b, ..., i = c(1,2)))' )),
    latent_variable('alpha', prior = list(mean = 'alpha', variance.hyper = 'sigma2_alpha'),
                    add_on = c('zeta(alpha = alpha, ...) +',
                               'alpha*h$eval(..., i = 4)'))
  ),
  
  # === regression parameter === #
  regression.parameter = list(
    regression_parameter('beta', 1, function(...) param$beta )
    #uniroot(function(beta) do.call(zeta.der, c(list(beta), args[-(7:8)])), lower = -1000, upper = 1000)$root )
    )
)
```

```{r saem}
# ---  Initialisation des paramètres --- #
param0 <- param %>% sapply(function(x) x* runif(1, 1.1,1.4))
#param0$rho2 = 0.2 ; param0$omega2 <- rep(.1,3)
param0$sigma2 <- 1
param0$alpha <- 0.2
#===============================================#
load.SAEM(model)
var0 <- init.SAEM(model, 
                  x0 = list(phi = c(1,80,4), gamma = 0, 
                            a = param0$a, b = param0$b, alpha = param0$alpha), 
                  sd = list(phi = c(.05, 1.5, .5), gamma = 0.1,
                            a = 2, b = 2, alpha = .05) )
#===================================================================================#
oracle <- max(do.call(S$eval, var.true), param)
oracle %>% unlist
```
# saem
```{r saem sans a b et alpha}
# exclude = c('gamma')
exclude = c('gamma', 'a', 'b')
load.SAEM(model, exclude)
var1 <- var0
var1[exclude] <- var.true[exclude]

res <- SAEM(200, 5, param0, var1, Phi, S$eval, max, sim,  eps = 1e-3,
            burnin = 50, 
            adptative.sd = 0.6, verbatim = 3 )

```

```{r plot, echo = F, fig.asp=0.8, fig.width=8}
plot(res, true.value = oracle )
plot(res, true.value = oracle, var = 'summary', time = F )
```
