---
title: "SAEM with proximal gradient descent"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

knitr::knit_hooks$set(time = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now, units = 's')
      # return a character string to show the time
      diff_time <- format(as.POSIXct(as.numeric(res), 
                                     origin = '1970-01-01', tz = 'UTC'), "%Mmin %Ssec")
      paste("Chunk execution time = ", diff_time)
    }
  }
}))

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.weightedidth = 12,
               fig.asp = 0.8,
               out.weightedidth = "100%")

require(SAEM4JLS)
require(tictoc)
```



```{r}
param <- list(sigma2 = 0.5,
              rho2 = .5,
              mu = 3)

J <- 10 ; n <- 50 ; p <- 20

time <- seq(-1,1, len = J)
ttime <- t(time)
S <- p*0.1#sample(1:p, 5) #c(50, 110, 155, 510, 750, 820)
U <- matrix(runif(n*p, min  = -1, max = 1), nrow = n, ncol = p)#1e4*as.matrix(x)
# U <- matrix(0, nrow = n, ncol = p) ; U[,1:S] <- 1
# U <- matrix(rnorm(n*p, 0, 1), nrow = n, ncol = p)
# for(i in 1:n) U[i,] <- sort(rnorm(p, 0, 1))

expand.grid(n = 1:n, p = 1:p) %>% mutate(U = as.numeric(U)) %>%
  ggplot(aes(n,p, fill = U)) + geom_tile() + scale_fill_gradient2()


tU <- t(U)
param$beta <- rep(0,p)
# param$beta[1] <- 1 ; param$beta[2] <- -1
param$beta[1:S] <- 1

eps <- matrix(rnorm(n*J, sd = sqrt(param$sigma2)), nrow = n)
Z <- rnorm(n, param$mu, sd = sqrt(param$rho2))

Y <- as.vector(param$beta %*% tU) + Z %*% ttime + eps
```

```{r data ploting, echo = F}
data.frame(Y) %>% mutate(id = 1:n) %>%
  melt(id = 'id', value.name = 'Y') %>%
  mutate(variable = rep(time, each = n)) %>% rename(time = variable) %>%
  ggplot(aes(time, Y, col = factor(id))) + geom_line() + theme(legend.position = 'null')
```


```{r SPGD res}
l <- function(beta, Z, param, ... ) 1/(2*param$sigma2) * sum( (Y - as.vector(beta %*% tU) - Z %*% ttime )^2 ) /n
grad.li <- function(beta, i, Z, ...)  -1/param$sigma2 * sum(Y[i,] - sum(beta * U[i,]) - Z[i]*time) * U[i,] /n
```


```{r SPGD test, eval=FALSE, include=FALSE}

res <- SPGD(200, theta0 = runif(p, -1,1),
            step = 1e-3,
            grad.li, n, l, Z, param, verbatim = T)

as.numeric(res)

plot(attr(res, 'f.value'))
plot(attr(res, 'gradf.value'))

l(param$beta, Z, param)
l(res, Z, param)

sapply(1:n,function(i) grad.li(res, i, Z)) %>% apply(1, sum) %>% abs %>% (base::max)

mean(abs(as.numeric(res) %*% tU - param$beta%*% tU)/param$beta%*% tU)
mean(abs(as.numeric(res) - param$beta))
```

```{r SAEM model}
model <- SAEM_model(
  function(sigma2, ...) - n*J/(2*sigma2),
  function(Z, beta, ...) mean( (Y - as.vector(beta %*% tU) - Z %*% ttime )^2 ),
  noise.name = 'sigma2',

  # === Variable Latente === #
  latent_vars = list(
    latent_variable('Z', dim = n, prior = list(mean = 'mu', variance = 'rho2'))
  ),

  # === Paramètre de regression === #
  regression.parameter = list(
    regression_parameter('beta', p, function(...) SPGD(1, theta0 = beta,
                                                      step = 1e-2,
                                                      grad.li, n, l, Z$Z, parameter) )
  )
)
```







```{r SAEM}
load.SAEM(model)
var0 <- init.SAEM(model,
                  x0 = list(Z = 0),
                  sd = list(Z = .1))

param0 <- list(sigma2 = 0.1, rho2 = 0.4, mu = 2.8, beta = rep(0, p))
oracle <- max(S = do.call(S$eval, c(param, list(Z=Z)) ), parameter = param, Z = list(Z=Z))

res <- SAEM(200, 10,
            param0, var0, Phi, S$eval, max, sim,
            adptative.sd = 0.6,
            burnin = 150,
            verbatim = 3)

plot(res, true.value = oracle, var = 'special', exclude = 'beta')

plot_high_dim(res, oracle, 'beta', dec = -1)
```

























