---
title: "Longitudinal data and nonlinear mixed model"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---
  
<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.weightedidth = 12,
               fig.asp = 0.8,
               out.weightedidth = "100%")

require(SAEM4JLS)
```

## Initialisation

```{r init}
m <- function(phi, eta) (phi[1] + eta)/(1+exp((phi[2]-t)/phi[3]))
#m <- function(phi, eta) phi[1] * t + phi[2]

ni <- 10 #nombre observation
ng <- 1 #nombre d'individu par groupe
G <- 20 # nombre groupe
F. <- 3#dimention du vecteur phi

n <- G*ng*ni #nombre total de data
N <- G*ng #nombre total d'individu

#=======================================#
param <- list(rho2 = 0.4,
              sigma2 = 0.5,
              mu = c(5,4,0.5),
              omega2 = c(0.5,0.1,0.01))
#=======================================#

eps <- rnorm(n, 0, sqrt(param$sigma2))
eta <- rnorm(N, 0, sqrt(param$rho2))
phi <- 1:G %>% sapply(function(i) rnorm(F., param$mu, sqrt(param$omega2)))

X <- data.frame('gen' = rep(1:G, each = ng) %>% as.factor) #Matrice de design
t <- seq(2,6, length.out = ni) #valeur des temps

# Y_{g,i,j} = m(s_j, phi_g) + \epsilon_{g,i,j}
# Y_{i,j} = m(s_j, phi_{X[i]}) + \epsilon_{i,j}
get.Y <- function(phi, eta) 1:N %>% sapply(function(i) m(phi[,X[i, 'gen']], eta[i]))
Y <- get.Y(phi, eta) + eps
#```

#```{r plot, echo = F}
data.frame(Y = Y, t = t ) %>% melt(id = 't') %>% mutate(gen = rep(X$gen, each = ni)) %>%
  ggplot(aes(t, value, col = variable, shape = gen)) + geom_point() + geom_line() +#+ theme(legend.position = 'null')
  guides(color = 'none')
```

## SAEM avec simulation par MCMC
$$\log f(Y, Z ; \theta) = \langle P(\theta) ; S(Y,Z) \rangle - \psi(\theta)$$

```{r setup stat exhaustive}
Phi <- function(rho2, sigma2, mu, omega2)
  c(- 1/(2*sigma2), -1/(2*rho2), -1/(2*omega2), mu/omega2)

S <- function(eta, phi)
{
  s <- c(sum((Y - get.Y(phi, eta))^2 ), #id = 1
    sum(eta^2),          #id = 2
    apply(phi^2, 1, sum),          #id = 3
    apply(phi  , 1, sum) )         #id = 4

  attr(s, '1') <- 1
  attr(s, '2') <- 2
  attr(s, '3') <- 2 + 1:nrow(phi)
  attr(s, '4') <- 1 + nrow(phi) + 1:nrow(phi)
  return(s)
}
```
## Metropolis Hastings

```{r MH}
#=============================================================================#
transi <- function(x) rnorm(length(x), x, 0.01)
loglik.phi <- function(x, eta, P)
{
  stat <- S(eta,x)
  # sum(P*stat)
  id <- c(1,2+1:F., 2+F.+1:F.) #indice de S_1 et S_{2,.} puis S_{3,.}
  sum(P[id]*stat[id])
}

loglik.eta <- function(x, phi, P) 
{ 
  stat <- S(x, phi)
  sum(P[1:2]*stat[1:2])
}
```

```{r MH phi}
phi.MH <- matrix(rnorm(F.*G, 0, 1), ncol = G, nrow = F.)
phi.MH <- MH_High_Dim(20000, phi.MH, transi, loglik.phi, eta, do.call(Phi, param), verbatim = T)

attr(phi.MH, 'acceptation_rate')

v <- attr(phi.MH, "value")
v %>% mutate(composante = factor(rep(1:nrow(phi.MH), max(v$iter)+1) )) %>% melt(id = c('iter', 'composante')) %>%
  ggplot(aes(iter, value, col = interaction(composante, variable))) + geom_line() + theme(legend.position = 'null') +
  labs(title = 'Resultat de Metropolis Hastings : phi', x = 'iteration', y = 'valeur de Z')

```

```{r MH eta}
eta.MH <- MH_High_Dim(10000, matrix(rnorm(N, 0, 1), nrow = 1), transi, loglik.eta,  phi, do.call(Phi, param), verbatim = T)

attr(eta.MH, 'acceptation_rate')



v <- attr(eta.MH, "value")
v %>% mutate(composante = factor(rep(1:nrow(eta.MH), max(v$iter)+1) )) %>% melt(id = c('iter', 'composante')) %>%
  ggplot(aes(iter, value, col = interaction(composante, variable))) + geom_line() + theme(legend.position = 'null') +
  labs(title = 'Resultat de Metropolis Hastings : eta', x = 'iteration', y = 'valeur de Z')


```




# SAEM
### initialisation
```{r SAEM init}
# --- Nombre iteration --- #
M <- 1
u <- function(k) 1
#---
para <- list( rho2 = sample(1:5, size = 1),
              sigma2 = sample(1:5, size = 1),
              mu = rep(0, F.),
              omega2 = rep(1, F.) )

etagivenY <- 1:M %>% lapply(function(i) rnorm(N, 0,1) )
phigivenY <- 1:M %>% lapply(function(i) rnorm(F.*G, 0,1) %>% matrix(ncol = G, nrow = F.) )
```

## Boucle

```{r SAEM}
sim <- function(niter, Phih, etagivenY, phigivenY)
{
  M <- length(phigivenY)
  etagivenY <- 1:M %>% lapply( function(i) 
    MH_High_Dim(niter, matrix(etagivenY[[i]], nrow = 1), transi, loglik.eta, phigivenY[[i]], Phih ))

  phigivenY <- 1:M %>% lapply( function(i)
    MH_High_Dim(niter, phigivenY[[i]], transi, loglik.phi, etagivenY[[i]], Phih ))

  list(eta = etagivenY, phi = phigivenY)
}

maxi <- function(S)
{
  mu <- S[attr(S,'4')]/G # = S[4]
  return(list(rho2 = S[attr(S,'2')]/N,
              sigma2 = S[attr(S,'1')]/n,
              mu = mu,
              omega2 = S[attr(S,'3')]/G - mu^2)
  )
}

niter <- 200
Z <- list(etagivenY, phigivenY)
res <- SAEM(niter, 10, u, para, Phi, S, Z, sim, maxi, eps = 1e-2, verbatim = T)
```




```{r res, echo = F}
dt <- res[[1]] %>% as.data.frame %>% na.omit

#Resultat de l'estimations
est <- rbind( param %>% unlist, dt[nrow(dt),]) %>%
  t %>% data.frame

names(est) <- c('Valeur réelle', 'Valeur estimée')
  
est <- est %>%
  mutate( Rrmse = abs(`Valeur réelle` -`Valeur estimée`)/max(abs(`Valeur réelle`)))
 
est %>% t %>%
  knitr::kable(caption = "résultat de l'algo SAEM-MCMC") %>%
  kable_styling(full_width = F)

# MCMC des paramètres
dt %>% mutate(i = 1:nrow(.)) %>% melt(id = 'i') %>%
  ggplot(aes(i, value, col = variable)) + geom_line() +
  labs(title = "représentation de l'algorithme SAEM pour les paramètres",
       x = 'iteration')

# MCMC de Z
v <- attr(res$Z, 'value')[[1]] %>% lapply(function(x) as.numeric(x)) %>% as.data.frame %>% t %>% as.data.frame()

v %>% mutate(i = 1:nrow(.)) %>% melt(id = 'i') %>% #mutate(phi = rep(factor(c(1:F.)), each = nrow(v)*G)) %>%
  ggplot(aes(i, value, col = variable)) + theme(legend.position = 'null') +
  geom_line() + 
  labs(title = "représentation des variables latentes de l'algorithme SAEM ",
       x = 'iteration')
```










