---
title: "Longitudinal and survival data modelisation"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)
rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 12, fig.asp = 0.8,
               fig.align = "center",
               out.weightedidth = "100%")

library(SAEM4JLS)
```

## Initialisation et génération des données

```{r number of cores, echo = F}
ncores <- pmin(2, future::availableCores()-1 )
message(paste('number of cores available =', ncores))
print(paste('number of cores available =', ncores))
```

```{r init}
#Phi[1] ; eta = valeur de fin  Phi[2] = valeur du noeud  Phi[3] = echelle
m <- function(t, eta, phi) (phi[,1] + eta)/(1+exp((phi[,2]-t)/phi[,3]))
#=======================================#
param <- list(sigma2 = 0.05,
              rho2 = 5,
              mu = c(90,90,5),
              omega2 = c(20, 40,1),
              #Survival data,
              nu2 = 0.5,
              a = 90,
              b = 30,
              alpha = 0.07,
              beta = 10)

#=======================================#
t <- seq(60,120, length.out = 10) #value of times

set.seed(18031997)
data <- JLS_data(G = 10, ng = 4, time = t, fct = m, param = param, linkfct = function(t,eta,phi) phi[,2]/phi[,3])

getDim(data)
#Sauvegarde des variables
Y <- data$obs
survival.time <- data@survival$obs
survival.time.log.sum <- sum(log(survival.time))
```

```{r data ploting, echo = F}
plot(data, nrow = 2)

# plt <- plot(data)
# gg <- data %>% ggplot(aes(time, obs, col = gen, group = id)) +
#   geom_line() + theme(legend.position = 'null') +
#   scale_y_continuous(breaks = 1:5*20) +
#   labs(title = 'Ostrinia attack proportion', y = 'percentage of attacked plant', x = 'Time')
# 
# ggsave('attack_proportion.png', gg, width = 6, height = 4)
# 
# gg <- plt$survival_plot +
#   labs(title = 'Flowering date', x = 'Time', y = '') +
#   scale_fill_discrete(name = "Flowering type", labels = c('late', 'early'))+
#   theme(legend.position = 'right')
# 
# ggsave('flowering_date.png', gg, width = 7, , height = 3)
```

# Statistique exhaustive
$$\log f(Y, Z ; \theta) = \langle \Phi(\theta) ; S(Y,Z) \rangle - \psi(\theta)$$

```{r  stat exhaustive}
sigma2_a <- sigma2_b <- sigma2_alpha <- 0.1

zeta <- function(beta, eta, phi, gamma, a,b, alpha)
{
  T1 <- data@survival$obs^(b-1) * data@survival$obs/b
  
  lbd <- function(t,g) exp(alpha*data@linkfct(t, eta[g], matrix(phi[g,], nrow = 1)))
  P1 <- T1 * sapply(1:nrow(data@survival),
                    function(i) lbd(data@survival$obs[i], data@survival$gen[i]) )
    # sapply(function(i) integrate(function(t) lbd(t,data@survival$gen[i]), 0, data@survival$obs[i])$value )

  P2 <- exp(beta*data@survival$U + as(rep(gamma, each = ng), 'matrix'))
  
  beta*sum(data@survival$U) -  b*a^-b * sum(P2*P1)
}

zeta.der <- function(beta, eta, phi, gamma, a, b, alpha)
{
  lbd <- function(t,g) t^(b-1) * exp(alpha*data@linkfct(t, eta[g], matrix(phi[g,], nrow = 1)))
  P1 <- 1:nrow(data@survival) %>% sapply(function(i) data@survival$obs[i]/b*lbd(data@survival$obs[i], data@survival$gen[i]) )
    # sapply(function(i) integrate(function(t) lbd(t,data@survival$gen[i]), 0, data@survival$obs[i])$value )

  P2 <- data@survival$U*exp(beta*data@survival$U + as(rep(gamma, each = ng), 'matrix'))
  
  sum(data@survival$U) -  b*a^-b * sum(P2*P1)
}

h <- fct_vector(function(a,b, ...) N*log(b*a^-b),
                function(b, ...) (b-1)*survival.time.log.sum,
                function(gamma,...) ng*sum(gamma),
                function(eta, phi, ...) sum(data@linkfct(survival.time, eta, apply(phi, 2, rep, ng) )) )

#==============================================================================#
model <- SAEM_model( 
            function(sigma2, ...) -n/(2*sigma2),
            function(eta, phi, ...) mean((Y - get_obs(data, eta = eta, phi = phi) )^2 ),
            latent_vars = list(
    latent_variable('eta', nrow = N, prior = list(variance = 'rho2'),
                    add_on = c('zeta(eta = x, ...)')),
    latent_variable('phi', nrow = G, ncol = F., prior = list(mean = 'mu', variance = 'omega2'),
                    add_on = c('zeta(phi = x, ...)')),
    latent_variable('gamma', nrow = N, prior = list(variance = 'nu2'),
                    add_on = c('zeta(gamma = x, ...) +',
                               'h$eval(gamma = x, ..., i = 3)')),

    latent_variable('a', nrow = 1, prior = list(mean = 'a', variance.hyper = 'sigma2_a'),
                    add_on = c('zeta(a = x, ...) +',
                               'h$eval(a = x, ..., i = 1)')),
    latent_variable('b', nrow = 1, prior = list(mean = 'b', variance.hyper = 'sigma2_b'),
                    add_on = c('zeta(b = x, ...) +',
                               'sum(h$eval(b = x, ..., i = c(1,2)))' )),
    latent_variable('alpha', nrow = 1, prior = list(mean = 'alpha', variance.hyper = 'sigma2_alpha'),
                    add_on = c('zeta(alpha = x, ...) +',
                               'x*h$eval(..., i = 4)'))
    ),
  
  # === Paramètre de regression === #
            regression.parameter = list(
    regression_parameter('beta', 1, function(...) param$beta )#uniroot(function(beta) do.call(zeta.der, c(list(beta), args[-(7:8)])), lower = -1000, upper = 1000)$root )
    )
)
```

# SAEM
## initialisation
```{r SAEM init}
# ---  Initialisation des paramètres --- #
para <- param %>% sapply(function(x) x* runif(1, 1.1,1.4))
# para$rho2 = 0.2 ; para$omega2 <- rep(.1,3)
para$alpha <- 0.2

# --- Initialisation des chaines MC : Z_0 --- #
Z <- getLatente(data, format = 'list')
Z$a = list(matrix(param$a))
Z$b = list(matrix(param$b))
Z$alpha = list(matrix(param$alpha))
Z$beta = list( matrix(param$beta) )
```

## Etape simulation et maximisation du SEAM
```{r SAEM fct}
maxi <- function(S)
{
  list(sigma2 = S%a%1,
       rho2 =   S%a%2,
       mu =     S%a%3,
       omega2 = S%a%4 - (S%a%3)^2,
       nu2 =    S%a%5,
       a =      S%a%6,  b =    S%a%8,
       alpha =  S%a%10, beta = S%a%12 )
}
# maxi(do.call(S$eval, c(getLatente(data), a = Z$a[[1]], b = Z$b[[1]], alpha = Z$alpha[[1]], beta = Z$beta[[1]])))
```

# Resultats

```{r SAEM loop setup}
sd.eta <- .8
sd.phi <- c(1, .3, .5)
sd.gamma <- 0.4
sd.a <-  0.2
sd.b <-  0.2
sd.alpha <- .05
```

# Tout

```{r SAEM gamma}
load.SAEM(model, exclude = c('eta', 'gamma','a', 'b', 'alpha', 'beta'))

# Z$eta = list(  matrix(rep(0, G*ng), ncol = 1) )
Z$phi = list(  matrix(rep(para$mu, G), nrow = F.) %>% t  )

gg <- simulation_test(sim, Phi, param, 300, Z) %>% lapply(function(z)plot(z[[1]], nrow = 2))



res <- SAEM(100, 5, para, Phi, S$eval, Z, sim, maxi, verbatim = 2)

plot(res, var = 'special', exclude = c('a', 'b', 'alpha','beta'),
     true.value = oracle(maxi, S, data, a = param$a, b = param$b, alpha = param$alpha, beta = param$beta))

Z$phi = list(data@phi)
Z$eta = list(data@eta)
```

# Juste a, b

## à partir de là : 200 iteration 10 simulation par step sur les 20 première puis 1

```{r SAEM ab}
load.SAEM(model, exclude = c('eta', 'phi', 'gamma', 'alpha', 'beta'))

Z$a = list(matrix(para$a)) ; Z$b = list(matrix(para$b))

res <- SAEM(200, function(k)ifelse(k<20, 20, 10), para, Phi, S$eval, Z, sim, maxi, verbatim = 2)

plot(res, var = 'special', exclude = c('a','b','alpha','beta'),
     true.value = oracle(maxi, S, data, a = param$a, b = param$b, alpha = param$alpha, beta = param$beta))

Z$a = list(matrix(param$a))  ; Z$b = list(matrix(param$b))
```


# Juste a, b et gamma

```{r SAEM ab et gamma }
load.SAEM(model, exclude = c('eta', 'phi', 'alpha', 'a', 'b', 'beta'))

Z$gamma = list(matrix(rep(0, G), ncol = 1))
# Z$a = list(matrix(para$a)) ; Z$b = list(matrix(para$b))
sd.gamma = 0.4
res <- SAEM(50, function(k)ifelse(k<3, 50, 5), para, Phi, S$eval, Z, sim, maxi, verbatim = 2)

plot(res, var = 'special', exclude = c('a','b','alpha','beta'),
     true.value = oracle(maxi, S, data, a = param$a, b = param$b, alpha = param$alpha, beta = param$beta))


Z$gamma = list(data@gamma)
Z$a = list(matrix(param$a)) ; Z$b = list(matrix(param$b))
```


# Juste alpha

```{r SAEM alpha, eval=FALSE, include=FALSE}
sim <- function(niter, h, Phih, eta, phi, gamma, a, b, alpha, verbatim = F)
{
  alpha <- list(MH_High_Dim_future( niter, alpha[[1]], sd = sd.alpha, loglik.alpha,
                                    eta[[1]], phi[[1]], gamma[[1]], a[[1]], b[[1]],
                                    Phih, cores = 1, verbatim = verbatim)  )
  
  list(eta = eta, phi = phi, gamma = gamma, a = a, b = b, alpha = alpha)
}

Z$alpha = list(matrix(para$alpha))

res <- SAEM(200, function(k)ifelse(k<20, 10, 1), para, Phi, S$eval, Z, sim, maxi, verbatim = 3)
my.plot(res)

Z$alpha = list(matrix(param$alpha))
```


# Juste a, b, alpha et gamma

```{r SAEM ab, alpha et gamma, eval=FALSE, include=FALSE}
sim <- function(niter, h, Phih, eta, phi, gamma, a, b, alpha, verbatim = F)
{
  gamma <- list(MH_High_Dim_future(niter, gamma[[1]], sd = sd.gamma, loglik.gamma,
                                   eta[[1]], phi[[1]], a[[1]], b[[1]], alpha[[1]],
                                   Phih, cores = 1, verbatim = verbatim) )
  
  a <- list(MH_High_Dim_future( niter, a[[1]], sd = sd.a, loglik.a,
                                eta[[1]], phi[[1]], gamma[[1]], b[[1]], alpha[[1]],
                                Phih, cores = 1, verbatim = verbatim) )

  b <- list(MH_High_Dim_future( niter, b[[1]], sd = sd.b, loglik.b,
                                eta[[1]], phi[[1]], gamma[[1]], a[[1]], alpha[[1]],
                                Phih, cores = 1, verbatim = verbatim)  )

  alpha <- list(MH_High_Dim_future( niter, alpha[[1]], sd = sd.alpha, loglik.alpha,
                                    eta[[1]], phi[[1]], gamma[[1]], a[[1]], b[[1]],
                                    Phih, cores = 1, verbatim = verbatim)  )
  
  list(eta = eta, phi = phi, gamma = gamma, a = a, b = b, alpha = alpha)
}

Z$alpha = list(matrix(para$alpha))
Z$gamma = list(matrix(rep(0, G), ncol = 1))
Z$a = list(matrix(para$a)) ; Z$b = list(matrix(para$b))

res <- SAEM(200, function(k)ifelse(k<20, 10, 1), para, Phi, S$eval, Z, sim, maxi, verbatim = 2)
my.plot(res)

Z$alpha = list(matrix(param$alpha))
Z$gamma = list(data@gamma)
Z$a = list(matrix(param$a)) ; Z$b = list(matrix(param$b))
```


```{r saem plot, echo = F }
# plot(res, true.value = oracle(maxi, S, data, a = param$a, b = param$b, alpha = param$alpha))
# plot.fitted.value(res, data)#, 1:100)
```


```{r seam table, results='asis', echo = F }
# plot(res, true.value = oracle(maxi, S, data, a = param$a, b = param$b, alpha = param$alpha), var = 'summary')
```








