---
title: "Proximal Gradient in a linear mixed effect"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
library(knitr)
library(kableExtra)

rm(list = ls())

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 12, fig.asp = 0.8,
               fig.align = "center",
               out.weightedidth = "50%")

library(SAEM4JLS)
```

## Initialisation

```{r number of cores, echo = F}
ncores <- pmin(1, future::availableCores() )
message(paste('number of cores available =', ncores))
print(paste('number of cores available =', ncores))
```

```{r init}
#Phi[1] ; eta = valeur de fin  Phi[2] = valeur du noeud  Phi[3] = echelle
m1 <- function(t, eta, phi) phi[,1] + eta
m2 <- function(t, eta, phi) 1/(1+exp((phi[,2]-t)/phi[,3]))
m <- function(t,eta, phi) m1(t,eta,phi) * m2(t,eta,phi)
#=======================================#
G <- 20
ng <- 4
N <- G*ng
F. <- 3
t <- seq(60,120, length.out = 10) #value of times
n <- length(t) * N
#=======================================#
param <- list(sigma2 = 0.05,
              mu = c(90,90,5),
              omega2 = c(20, 40,1) )
#=======================================#
phi <- t(matrix( rnorm(G*F., mean = param$mu, sd = sqrt(param$omega2)),
               nrow = F.))

eps <- rnorm(n, mean = 0 , sd = sqrt(param$sigma2) )

p <- 2
U <- 10*matrix(runif(N*p), nrow = N, ncol = p)#1e4*as.matrix(x)
tU <- t(U)
beta <- matrix(rep(0, p), nrow = 1) ; beta[sample(1:p, 1)] <- 1



time <- rep(t, N)
get_obs <- function(beta, phi) m(time, rep( as.vector(beta %*% tU), each = length(t)), apply(phi, 2, rep, each = ng* length(t)))

get_obs_i <- function(beta, phi, i) m(t, sum(beta %*% tU[,i]), matrix(rep(phi[(i-1)%%G+1,], each = length(t)),ncol = F.) )


data <- data.frame(id = rep(1:N, each = length(t)) , time = rep(t, N), gen = rep(1:G, each = ng*length(t))) %>%
  mutate(obs = get_obs(beta, phi) + eps)

Y <- data$obs %>% matrix(ncol = N) %>% t
```

```{r data ploting, echo = F} 

data %>% ggplot(aes(time, obs, col = factor(gen), group = id)) +
  geom_line() + theme(legend.position = 'null')
```






```{r SPGD}

proxi <- function(theta, gamma, alpha, lambda)
{
  coef <- ifelse(theta > gamma*alpha*lambda, theta-gamma*alpha*lambda,
                 ifelse(theta < -gamma*alpha*lambda, theta+gamma*alpha*lambda, 0))
  1/(1+gamma*lambda*(1-alpha)) * coef
}

prox <- function(theta, gamma, alpha, lambda) sapply(theta, proxi, gamma, alpha, lambda)

SPGD <- function(niter, m, theta0, n, step = 1e-6, grad.fi, f, ...)
{
  gamma <- step
  if(!is.function(step)) gamma <- function(k) step


  args <- list(...)
  if(length(args) == 1 && is.list(args[[1]])) args <- args[[1]]

  theta.tilde <- theta0
  theta.t <- matrix( rep(theta0, m+1), nrow = m+1)
  grad.f.tilde <- sapply(1:n, function(i) do.call(grad.fi, c(list(theta.tilde, i), args)))

  f.value <- rep(NA, niter+1)
  f.value[1] <- do.call(f, c(list(theta.tilde), args))

  k <- 1
  while(k < niter  && mean(abs(grad.f.tilde)) > 1e-3)
  {
    for(t in 1:m+1)
    {
      i <- sample(1:n, 1) #Tirage dans une uniform

      grad.f.hat <- do.call(grad.fi, c(list(theta.t[t-1,], i), args))#approxMCMC()

      d <- grad.f.hat+ mean(grad.f.tilde) - grad.f.tilde[i]
      theta.t[t,] <- prox(theta.t[t-1,] - gamma(k)*d, gamma(k), 1, 0)
    }
    theta.tilde <- apply(theta.t, 2, mean)
    grad.f.tilde <- sapply(1:n, function(i) do.call(grad.fi, c(list(theta.tilde, i), args)))

    # print(mean(grad.f.tilde))
    f.value[k+1] <- do.call(f, c(list(theta.tilde), args))
    theta.t[1,] <- theta.tilde

    k <- k + 1
  }

  theta.tilde <- matrix(theta.tilde, nrow = 1)
  attr(theta.tilde, 'f.value') <- na.omit(f.value)

  return(theta.tilde)
}



model <- SAEM_model(
  function(sigma2, ...) - n/(2*sigma2),
  function(phi, beta, ...) mean( (Y - get_obs(beta, phi) )^2 ),

  # === Variable Latente === #
  latent_vars = list(
    latent_variable('phi', nrow = G, ncol = F., prior = list(mean = 'mu', variance = 'omega2'))
    ) )

Phi <- model$Phi$eval

l <- function(beta, phi, Phi, ... ) Phi%a%1 * mean( (Y - get_obs(beta, phi) )^2 ) /n
grad.li <- function(beta, i, phi, Phi,...)  Phi%a%1 * mean( (Y[i,] - get_obs_i(beta, phi, i) ) )* U[i,] /n
```

```{r SPGD res}
res <- SPGD(500, 10, theta0 = matrix(rep(0, p), nrow = 1), n = N,
            step = burnin_fct(200, 0.8, 1e-5), grad.li, l, phi, Phi = do.call(Phi, param))

as.numeric(beta)
plot(attr(res,'f.value'))
as.numeric(res)
sum(beta - round(as.numeric(res)))
```



## SAEM avec simulation par MCMC
$$\log f(Y, Z ; \theta) = \langle \Phi(\theta) ; S(Y,Z) \rangle - \psi(\theta)$$

```{r  stat exhaustive}

model <- SAEM_model(
  function(sigma2, ...) - n*J/(2*sigma2),
  function(Z, beta, ...) mean( (Y - as.vector(beta %*% t(U)) - Z %*% t(time) )^2 ),

  # === Variable Latente === #
  latent_vars = list(
    latent_variable('Z', nrow = n, prior = list(mean = 'mu', variance = 'rho2'))
    ),

  # === Paramètre de regression === #
  regression.parameter = list(
    regression_parameter('beta', p, function(...)SPGD(100, 10, theta0 = beta[[1]],
                                                   step = burnin_fct(15, 0.8, 1e-5),
                                                   grad.li, l, ...) )
    )
  )


Phi <- model$Phi$eval
S <- model$S

loglik.phi <- model$loglik.fct$phi
sim <- model$simulation.fct
```
