---
title: "Test variance"
author: "Antoine caillebotte"
date: "`r Sys.time()`"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1000px;
  margin-left: auto;
  margin-right: auto;
}
</style>
  
```{r setup, include = F}
rm(list = ls())

library(knitr)
library(kableExtra)

knitr::knit_hooks$set(time = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now, units = 's')
      # return a character string to show the time
      diff_time <- format(as.POSIXct(as.numeric(res), 
                                     origin = '1970-01-01', tz = 'UTC'), "%Mmin %Ssec")
      paste("Chunk execution time = ", diff_time)
    }
  }
}))

opts_chunk$set(echo = T, message = F, warning = F,
               fig.width = 12, fig.asp = 0.8,
               fig.align = "center",
               out.weightedidth = "100%")

library(SAEM4JLS)
```

## Initialisation et génération des données

```{r number of cores, echo = F}
ncores <- pmin(1, future::availableCores()-1 )
message(paste('number of cores available =', ncores))
print(paste('number of cores available =', ncores))
```

```{r init}
#Phi[1] ; eta = valeur de fin  Phi[2] = valeur du noeud  Phi[3] = echelle
m <- function(t, eta, phi) (phi[,1] + eta)/(1+exp((phi[,2]-t)/phi[,3]))
#=======================================#
param <- list(sigma2 = 0.05,
              rho2 = 0.1,
              mu = c(5,90,5),
              omega2 = c(0.5,0.1,0.01),
              #Survival data,
              nu2 = 0.5,
              a = 90,
              b = 50,
              alpha = 7,
              beta = 10)

#=======================================#
t <- seq(60,120, length.out = 10) #value of times

dt_NLME <- NLME_data(G = 10, ng = 12, time = t, fct = m, param = param)
dt_SF <- SF_obs(dt_NLME, param, m)

getDim(dt_NLME)
Y <- dt_NLME$obs
source('joint_model.R')
```

```{r data ploting, echo = F}
gg1 <- dt_NLME %>% ggplot(aes(time, obs, col = gen, group = id)) + 
  geom_point() + geom_line() + theme(legend.position = 'null')
# --- Survival data --- #
gg2 <- dt_SF %>% ggplot(aes(obs, fill = factor(U))) + 
  geom_histogram(col = 'white', position = 'identity', bins = 30) + theme(legend.position = 'null')

grid.arrange(gg1, gg2, nrow = 2) ; rm(gg1, gg2)

affichage <- function(res)
{
  res@chain <- list(phi = res@chain$phi)
  plt1 <- plot(res, var = 'MCMC', true.value = list(mu = param$mu))
  
  plt2 <- plot(res@Z$phi[[1]], 'acceptation') %>%
    vline(correction.phase*MH.iter(correction.phase), col = 'orange')

  grid.arrange(plt1, plt2, nrow = 2)
}
```




# Resultats

```{r oracle, echo = F, results='asis'}
data.frame( Oracle = maxi(S$eval( dt_NLME@eta, dt_NLME@phi, 
                            attr(dt_SF, 'gamma'), param$a, param$b, param$alpha  )) %>% unlist ,
            Initialisation = para%>% unlist)%>% t %>% round(digits = 4) %>% 
  knitr::kable(format = 'html') %>% kable_styling(full_width = F)
```
Légende des graphs : En pointillé les moyennes à priori, la ligne vertical orange symbolise la phase de correction
```{r SAEM loop, time = T }
niter <- 10*3
correction.phase <- 15
MH.iter <- function(k) ifelse(k<=correction.phase, 100, 100)

sd.eta <- function(k) 0.04
sd.phi <- function(k) ifelse(k<=correction.phase, 0.5, 0.05 )

sd <- seq(0.05, 1.5, length.out = 20)
for(i in 1:length(sd))
{
  message(paste0('===============================================================================', i))
  print(sd[i])
  sd.phi <- function(k) ifelse(k<=correction.phase, sd[i], 0.05 )
  res <- SAEM(niter, MH.iter, para, Phi, S$eval, Z, sim, maxi, eps = 1e-3, verbatim = 2)
  affichage(res)
}
```











